/*
 * lcs_app.h
 *
 * Copyright (c) 2022-2025 EnOcean
 * SPDX-License-Identifier: MIT
 * See LICENSE file for details.
 * 
 * Title:   LON Stack Application Layer Event Handlers
 * Purpose: Implements the application-specific event handlers for the 
 *          LON application layer (Layer 7).
 * Notes:   See ISO/IEC 14908-1, Section 10 for LON protocol details.
 *
 *          All messages coming into the application layer are handled by
 *          the APPReceive() function, which dispatches messages to the
 *          appropriate "Handle" function. Some of the functions explained
 *          here are local to the application layer and are not available 
 *          to the application program. See "Local Function Prototypes" 
 *          section below.  The main functions in this file are:
 *
 *          HandleNormal():   Handles normal messages bound to the application program.
 *                            These are messages from other nodes that are bound to the
 *                            application program.
 *
 *          HandleResponse(): Handles normal responses bound to the application program.
 *                            These are responses due to requests generated by the
 *                            application program.
 *
 *          ProcessNV():      Handles incoming NV update and poll messages.
 *                            These are messages from other nodes or responses for
 *                            requests generated by the application layer.
 *
 *          SendVar():        Takes care of network variable updates waiting to be sent.
 *                            i.e implicit messages generated due to output network variable
 *                            updates in the application program.
 *
 *          PollVar():        Takes care of network variable polls waiting to be dispatched.
 *                            These are messages explicitly generated by the application
 *                            program by calling various forms of poll functions.
 *                            The corresponding variables are input network variables.
 *
 *          HandleNM():       Processes network management messages. Defn is in netmgmt.c.
 *
 *          HandleND():       Processes network diagnostic messages. Defn is in netmgmt.c.
 *
 *          HandleProxyResponse(): Handles responses from proxy messages. Defn is in
 *                            netmgmt.c. i.e responses received from the target node
 *                            are relayed back to the original node.
 *
 *          HandleMsgCompletion(): Handles transaction completion indications from
 *                            transport, session, and network layers. Some of them
 *                            are for transactions originated by the application
 *                            layer itself. Others are for transactions originated
 *                            by the application program. In that case, the
 *                            application program is notified of these completion
 *                            events by a call to MsgCompletes or NVUpdateCompletes
 *                            function.
 *
 *          TryMsgSend():     Helper function that moves messages in the application
 *                            queue to lower layer queues as appropriate.
 *
 *                            All messages generated by the application program
 *                            (implicit or explicit) are queued and then sent to 
 *                            lower layers by the APPSend() function.
 *
 *          APPReset():       Handles the application layer reset operations. 
 *                            Allocates memory for all queue structures used 
 *                            by the application. Also, performs initialization
 *                            required after each reset.
 *
 *          APPInit():        Handles initialization required only during initial
 *                            power up.
 *
 *          AddNV():          Handles network variable declarations in the application
 *                            program. This function is normally called during power up
 *                            to register all network variables in application program.
 *                            This is done using the function AppInit(). Note that APPInit()
 *                            is application layer function whereas AppInit() is application
 *                            program function.
 *
 *          The functions in this file also support the API interface used by application
 *          programs such as msg_send(), resp_send(), and propagate().
 *
 *          There is no implicit way of sending network variable updates in this
 *          implementation. The application program must call Propagate or one
 *          of its variants to propagate network variable updates.
 */

#ifndef _LCS_APP_H
#define _LCS_APP_H

/*------------------------------------------------------------------------------
Section: Includes
------------------------------------------------------------------------------*/
#include <string.h>
#include "izot/IzotPlatform.h"
#include "izot/lon_types.h"
#include "abstraction/IzotEndian.h"
#include "lcs/lcs_api.h"
#include "lcs/lcs_timer.h"
#include "lcs/lcs_eia709_1.h"
#include "lcs/lcs_iup.h"
#include "lcs/lcs_node.h"
#include "lcs/lcs_netmgmt.h"
#include "lcs/lcs_network.h"
#include "lcs/lcs_proxy.h"
#include "lcs/lcs_queue.h"
#include "lcs/lcs_tsa.h"

/*------------------------------------------------------------------------------
Section: Constant Definitions
------------------------------------------------------------------------------*/

/*******************************************************************************
Define tags for use by the application layer for the messages it generates.
There are several types of messages the application layer generates. Proxy,
ManualServiceRequest, network variable updates, and network variable polls. The tag
for these messages will be set up in such a way that we can tell what type of
message got completed when the application layer receives completion indication
from transport/session layer. Since tags are also used by the application
program and they are all >= 0, we will use negative tags for the application
layer. For tags for the application layer are used as follows:

0xFFFF   ==> tag for manual service request.
For all NV tags,
bit15 is 1 (negative tag)
bit14 is 1 => nv update 0 => nv poll
bit13 is 1 => last tag.
bit12-bit0 is the actual primary index of network variable.

The tag for which bit13 is set is a special tag value that is recognized
by transport layer. In this case, the transport layer sends an indication
right away with that tag. No message is sent by the transport layer.

Network variable updates and polls are scheduled sequentially. When the
completion event for the last tag is received, completion event is
generated.
*******************************************************************************/
#define MANUAL_SERVICE_REQ_TAG_VALUE ((MsgTag) 0xFFFF)
#define NV_UPDATE_LAST_TAG_VALUE ((MsgTag) 0xE000)
#define NV_POLL_LAST_TAG_VALUE   ((MsgTag) 0xA000)

#define MANUAL_SERVICE_REQUEST_TAG(tag)  (tag == MANUAL_SERVICE_REQ_TAG_VALUE)

#define NV_UPDATE_TAG(tag)    ((tag & 0xC000) == 0xC000)
#define NV_POLL_TAG(tag)      ((tag & 0xC000) == 0x8000)
#define NV_INDEX_OF_TAG(tag)  (tag & 0x1FFF)
#define NV_LAST_TAG(tag)      ((tag & 0xA000) == 0xA000)

#define GET_NV_UPDATE_TAG(index)      (0xC000 | index)
#define GET_NV_POLL_TAG(index)        (0x8000 | index)

/* Explicit application message codes */
#define APPL_MSG_OFFLINE       0x3F
#define FOREIGN_FRAME_OFFLINE  0x4F

/*------------------------------------------------------------------------------
Section: Function Prototypes
------------------------------------------------------------------------------*/
LonStatusCode APPInit(void);
void APPReset(void);
void APPSend(void);
void APPReceive(void);
LonStatusCode SendResponse(RequestId reqId, IzotByte code, int len, IzotByte *pData);
LonStatusCode SendNullResponse(RequestId reqId);
LonStatusCode AllocSendUnackd(PktCtrl ctrl, MsgTag tag, IzotSendAddress* pSrc, DestinType code, IzotByte data0, int len, IzotByte *pData);
uint32_t GetSiDataLength(void);
void IzotPrepareNetworkData(IzotByte *ndi, IzotUbits16 dpIndex, IzotUbits16 dpLen, IzotByte *hdi);
LonStatusCode IzotNdiToHdi(const IzotByte *ndi, IzotByte *hdi, const IzotByte *ibol);

#endif  // _LCS_APP_H
